blank_issues_enabled: false
contact_links:
  - name: Issue tracker on Codeberg
    url: https://codeberg.org/Lich-Corals/linux-file-converter-addon/issues
    about: Please ask and answer questions here.
